server:
  host: "127.0.0.1"
  port: 8888

database:
  mysql:
    url:  "root:12345678@tcp(127.0.0.1:3306)/go_blog?charset=utf8mb4&parseTime=True&loc=Local"
    max_idle_conn: 8
    max_open_conn: 1000
    max_idle_time: 30

redis:
  host: "192.168.188.5"
  port: 15517
  auth: "1Y7Fk[7&%_hh*"
  read_timeout: 10
  write_timeout: 10
  min_idle_conn: 8

jwt:
  secret_key: "abc_2025*Blog"
  expire_hour: 12


